version: "3"

services:
  flarum:
    #image: mondedie/flarum:stable
    #image: bfaf953e8895
    build: /home/tim/projects/flarum-docker/flarum-image
    container_name: flarum
    environment: 
      - UID=nginx
      - GID=nginx
    env_file:
      - ./flarum.env
    volumes:
      - ./assets:/flarum/app/public/assets
      - ./extensions:/flarum/app/extensions
      - ./nginx:/etc/nginx/flarum
    ports:
      - 443:8888
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=flarumpass
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=flarumpass
    volumes:
      #- ./mysql/initdb:/docker-entrypoint-initdb.d # uncomment if you have a flarum dump
      - ./mysql/db:/var/lib/mysql
